version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_backend
    ports:
      - "3000:3000"
    environment:
      - DB_PATH=/app/data/ft_transcendence.db
      - NODE_ENV=production
      - FRONTEND_URL=http://50.19.72.26:5173
      - BACKEND_URL=http://50.19.72.26:3000
      - ENABLE_HTTPS=false
      - LOG_LEVEL=info
      - JWT_SECRET=your-super-secure-jwt-secret-key-at-least-32-characters-long-and-random
    volumes:
      - ./data:/app/data
      - ./logs/backend:/app/logs
    working_dir: /app
    restart: unless-stopped
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./certs:/app/certs
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    networks:
      - app_network

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: ft_sqlite_web
    ports:
      - "8086:8080"
    volumes:
      - ./data:/data
    command: python -m sqlite_web -H 0.0.0.0 -x /data/ft_transcendence.db
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  frontend_node_modules: