version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/ft_transcendence.db
    volumes:
      - ./data:/app/data
    working_dir: /app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    restart: unless-stopped

  sqlite-web:
    image: coleifer/sqlite-web
    platform: linux/amd64
    container_name: ft_sqlite_web
    ports:
      - "8086:8080"
    volumes:
      - ./data:/data
    command: ["sqlite_web", "/data/ft_transcendence.db", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - backend
    restart: unless-stopped
