version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app

