version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/ft_transcendence.db
    volumes:
      - ./data:/app/data
    working_dir: /app
    restart: unless-stopped
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: ft_frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   restart: unless-stopped

