global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'elk-monitor'

rule_files:
  # Add alerting rules here

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s 