# Server configuration
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601
server.publicBaseUrl: "http://localhost:5601"

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000

# Security settings
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "${KIBANA_ENCRYPTION_KEY}"
xpack.reporting.encryptionKey: "${KIBANA_REPORTING_KEY}"
xpack.security.encryptionKey: "${KIBANA_SECURITY_KEY}"

# Session configuration
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "24h"
xpack.security.cookieName: "sid"

# Login configuration
xpack.security.loginAssistanceMessage: "Please contact your administrator for access"
xpack.security.loginHelp: "Use your assigned credentials to log in"

# Audit logging
xpack.security.audit.enabled: true
xpack.security.audit.appender.type: "file"
xpack.security.audit.appender.fileName: "/usr/share/kibana/logs/kibana_audit.log"
xpack.security.audit.events.include: ["saved_object_resolve", "saved_object_create", "saved_object_update", "saved_object_delete"]

# Content Security Policy
csp.rules: [
  "default-src 'self'",
  "script-src 'self' 'unsafe-eval' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self'",
  "frame-ancestors 'self'"
]

# Security headers
server.customResponseHeaders: {
  "X-Frame-Options": "SAMEORIGIN",
  "X-Content-Type-Options": "nosniff",
  "X-XSS-Protection": "1; mode=block",
  "Referrer-Policy": "strict-origin-when-cross-origin"
}

# Disable features for security
telemetry.enabled: false
telemetry.optIn: false
newsfeed.enabled: false
xpack.reporting.csv.enablePanelActionDownload: false

# Logging
logging.appenders.file.type: file
logging.appenders.file.fileName: /usr/share/kibana/logs/kibana.log
logging.appenders.file.layout.type: json
logging.root.level: warn
logging.loggers:
  - name: elasticsearch.query
    level: warn
  - name: http.server.response
    level: warn