api.auth.basic.password: ${LOGSTASH_PASSWORD}
api.auth.basic.username: logstash
api.auth.type: basic
api.https.host: 0.0.0.0
api.https.port: 9600
api.ssl.enabled: false
path.config: /usr/share/logstash/pipeline
path.queue: /usr/share/logstash/data/queue
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.unsafe_shutdown: false
pipeline.workers: 2
queue.max_bytes: 1gb
queue.max_events: 0
queue.type: persisted
xpack.monitoring.elasticsearch.hosts:
- https://elasticsearch:9200
xpack.monitoring.elasticsearch.password: qfpOAarca6BFMvu0CfOpDqGds
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
